const userTypes = {
  SET_CURRENT_USER: `SET_CURRENT_USER`,
  SET_LOGGED_IN: `SET_LOGGED_IN`,
  SET_LOGGIN_ERROR: `SET_LOGGIN_ERROR`,
  SET_USER_PROFILE: `SET_USER_PROFILE`
}

export default userTypes;
